language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - rbx
  - ruby-head
  - jruby
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby
    - rvm: jruby-head
script: bundle exec rake mutant